name: 'Close stale issues'
on:
  schedule:
    # Run daily
    - cron: '30 */4 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is being marked stale because it has not had any activity for 1 days. Reply below within 1 days if it should be left open.'
          days-before-stale: 1
          days-before-close: 1
          stale-issue-label: 'Stale'
          only-labels: 'User Support'
          exempt-all-assignees: true
          exempt-all-milestones: true
